### ISSUE TITLE
ページ内リンク設定見直し

### ISSUE THREAD

**Issue by TAKUOO** [TAKUOO/monobank#16]
#### やること
リンクが繋がれてなかったり、disableになっている箇所があるのでリンクをつなぐ、disableに見た目が変わっているところを変更する。

#### 背景
段階的な作成を進めてきた為、リンクがつながっていなかったりしています。現在全ページが公開している為、リンク設定されてないものを見直しきちんと設定していく

画像は一部です。全ページの見直しが必要です。
![スクリーンショット 2021-03-17 8 47 11](https://user-images.githubusercontent.com/39471524/111394199-959eeb00-86fd-11eb-8ade-fc29c2d6f58c.png)
![スクリーンショット 2021-03-17 8 47 19](https://user-images.githubusercontent.com/39471524/111394204-99327200-86fd-11eb-8842-ad1c3308720c.png)

**Comment by mebius-design** [comment]
こちら確認させて頂いています。
全ページのリンク未実装先の検出と確認、実装に
1時間ほど、お時間を頂くかもしれません。

**Comment by TAKUOO** [comment]
了解です！これ完了したらチラシの方お願いしますm(_ _)m

**Comment by mebius-design** [comment]
承知いたしました！
14時半頃から作業を再開させて頂きます。

**Comment by mebius-design** [comment]
monobankページ内を一通り拝見させて頂きました。
リンク未設定が確認できた内容を、下記に記載させて頂きます。

固定ページ、投稿を探してもリンク先が、わからない内容がありましたので
併せてご教授頂けますと幸いですmm

——————————————————-

●買取　ページ

来店買取　宅配買取　出張買取　＞　STEP3査定額の算出    高額査定のコツ
　URLを教えて頂きたいです
　（　/useful/urukotsu/★商品を高く売るコツ★.html  でしょうか？　）

宅配買取　＞　宅配買取の安心配送保険　商品売却前の予備知識
　URLを教えて頂きたいです

——————————————————-

●フッター

お問い合わせ
　URLを教えて頂きたいです

会社概要
　URLを教えて頂きたいです

**Comment by TAKUOO** [comment]
@mebius-design 
こちらでお願いします！
> /useful/urukotsu/★商品を高く売るコツ★.html でしょうか？　

https://monobank.jp/category/useful/urukotsu

> URLを教えて頂きたいです
https://monobank.jp/category/useful/knowledge

> フッター
こちらは今のところないのでこのままでOKです！

**Comment by mebius-design** [comment]
早速のご対応ありがとうございます！
承知いたしました。

**Comment by mebius-design** [comment]
編集に関して質問です。
monobank 　買取ページ　に関しては
（phpファイルではなく）固定ページ内に、情報があるようですが
本番サイトにログインの上、編集を行う流れでよろしいでしょうか？

また上記の解釈で間違いない場合
編集画面で以下のような画面になる（ブロックのリカバリーを施行　を押さないと編集できない）のですが
ブロックのリカバリーを施行　を押した上で編集を進めてよろしいでしょうか？
![スクリーンショット 2021-03-25 15 36 05](https://user-images.githubusercontent.com/52993138/112429517-1b670a00-8d80-11eb-89b9-1885c0a58385.png)

**Comment by TAKUOO** [comment]
であれば本番環境のものを触ってもらっていいですか？

**Comment by mebius-design** [comment]
ありがとうございます！
上記の添付画像についても、本番環境の内容になっていますので
ブロックのリカバリーを施行　をした上で進めさせて頂ければと思います。

**Comment by mebius-design** [comment]
本件、修正完了しましたので
ご確認、よろしくお願いいたします。
https://monobank.jp/purchase

**Comment by TAKUOO** [comment]
有難うございます！
各店舗のフォーム形のところのリンクもあるんですが、こちらはおいおいにしましょう。
https://monobank.jp/shop/shimonoseki-brandshop/inquiry
一旦完了で問題ないです。

**Comment by mebius-design** [comment]
ご確認頂きありがとうございます！
＞各店舗のフォーム形のところのリンク
上記は失礼いたしましたmm
次回以降で、対応させて頂けますと幸いです。

**Comment by TAKUOO** [comment]
こちら引き続きお願いしたいので、Todoに戻します！

**Comment by TAKUOO** [comment]
各店舗の来店予約フォームの買取流れの高額査定のコツのリンク設定

**Comment by TAKUOO** [comment]
@mebius-design 
こちら僕の方でやっときましのたでissueをcloseします！
